### ISSUE TITLE
Trying to run shieldy locally doesnt work

### ISSUE THREAD

**Issue by RonQen** [1inch/shieldy#140]
Unfortunately I cant connect the Docker to the DB. I can connect to the DB manually via shell though. Can someone help me solve the issue?

```
wait-dependencies_1  | wait-for-it.sh: waiting 1 seconds for 127.0.0.1:27017
wait-dependencies_1  | wait-for-it.sh: timeout occurred after waiting 1 seconds for 127.0.0.1:27017
shieldy_1            | [Bot]     at promiseOrCallback (/usr/src/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
shieldy_1            | [Bot]     at Mongoose.connect (/usr/src/app/node_modules/mongoose/lib/index.js:341:10)
shieldy_1            | [Bot]     at Object.<anonymous> (/usr/src/app/dist/models/index.js:5:10)
shieldy_1            | [Bot]     at Module._compile (internal/modules/cjs/loader.js:999:30)
shieldy_1            | [Bot]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
shieldy_1            | [Bot]     at Module.load (internal/modules/cjs/loader.js:863:32)
shieldy_1            | [Bot]     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
shieldy_1            | [Bot]     at Module.require (internal/modules/cjs/loader.js:887:19)
shieldy_1            | [Bot]     at require (internal/modules/cjs/helpers.js:74:18)
shieldy_1            | [Bot]     at Object.<anonymous> (/usr/src/app/dist/middlewares/messageSaverWorker.js:6:1)
shieldy_1            | [Bot]     at Module._compile (internal/modules/cjs/loader.js:999:30)
shieldy_1            | [Bot]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
shieldy_1            | [Bot] (node:112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which    was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1   )

```

**Comment by backmeupplz** [comment]
ask @masaruhoshi about Docker :) they are the ones who built the latest docker file (https://github.com/1inch/shieldy/pull/110)
